# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

jobs:
  # Single deploy job since we're just deploying
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Setup Pages
        uses: actions/configure-pages@v3
        with:
          node-version: 16
      - name: pnpm-setup
        uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Install and Build
        run: |
          pnpm install --no-frozen-lockfile
          pnpm run build
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.2.2
        with:
          ACCESS_TOKEN: ${{ secrets.YANGADMINTOKEN }}
          GITHUB_TOKEN: ${{ secrets.YANGADMINTOKEN }}
          branch: gh-pages
          folder: yang-amdin.org
